[[index]]
url = "http://inf-repo-02.lynxhedge.se/repository/lynx-pypi/simple"
default = true
allow-insecure = true

[[index]]
url = "https://inf-repo-02.lynxhedge.se/repository/pypi/simple"
allow-insecure = true

allow-insecure-host = ["https://inf-repo-02.lynxhedge.se/repository/pypi/simple"]

use-native-tls = true
